# Generated by Django 4.1.1 on 2023-02-26 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(default="", max_length=100, verbose_name="Nombre"),
                ),
                (
                    "apellido_p",
                    models.CharField(
                        default="", max_length=150, verbose_name="Apellido paterno"
                    ),
                ),
                (
                    "apellido_m",
                    models.CharField(
                        default="", max_length=150, verbose_name="Apellido materno"
                    ),
                ),
                (
                    "genero",
                    models.CharField(default="", max_length=100, verbose_name="Genero"),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True,
                        default=None,
                        max_length=15,
                        null=True,
                        verbose_name="Fecha nacimiento",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        default="", max_length=150, verbose_name="Residencia"
                    ),
                ),
                ("telefono", models.IntegerField(default=0, verbose_name="Teléfono")),
                (
                    "correo",
                    models.CharField(default="", max_length=100, verbose_name="Correo"),
                ),
                ("estatura", models.FloatField(default=0, verbose_name="Estatura")),
                ("peso", models.FloatField(default=0, verbose_name="Peso")),
                (
                    "enfermedades",
                    models.CharField(
                        default="",
                        max_length=250,
                        verbose_name="Enfermedades crónicas o padecimiento",
                    ),
                ),
                (
                    "alergias",
                    models.CharField(
                        default="", max_length=200, verbose_name="Alergias"
                    ),
                ),
                (
                    "dulces",
                    models.CharField(
                        default="",
                        max_length=300,
                        verbose_name="¿Prefieres consumir alimentos dulces o salados?",
                    ),
                ),
                ("hr_entrenamiento", models.CharField(max_length=20)),
                ("hr_despertar", models.CharField(max_length=10)),
                ("hr_dormir", models.CharField(max_length=20)),
                (
                    "proteinas",
                    models.CharField(
                        default="",
                        max_length=300,
                        verbose_name="Elige 3 de estás proteinas",
                    ),
                ),
                (
                    "carbohidratos",
                    models.CharField(
                        default="", max_length=300, verbose_name="Elige 3 Carbohidratos"
                    ),
                ),
                (
                    "comidas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=400,
                        null=True,
                        verbose_name="¿Cuales son tus comidas favoritas?",
                    ),
                ),
                (
                    "objetivo",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=300,
                        null=True,
                        verbose_name="¿Cuales es tu objetivo a conseguir?",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estatura", models.FloatField(default=0, verbose_name="Estatura")),
                ("peso", models.FloatField(default=0, verbose_name="Peso")),
                ("medidas", models.CharField(max_length=15, verbose_name="Medidas")),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pagos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "servicio_contratado",
                    models.CharField(
                        default="",
                        max_length=60,
                        verbose_name="Tipo de servicio contratado",
                    ),
                ),
                (
                    "tipo_pago",
                    models.CharField(max_length=150, verbose_name="Tipo de pago"),
                ),
                (
                    "costo",
                    models.IntegerField(default=0, verbose_name="Costo del servicio"),
                ),
                (
                    "aceptado",
                    models.BooleanField(default=False, verbose_name="Aceptar?"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.cliente",
                    ),
                ),
            ],
        ),
    ]
