# Generated by Django 4.1.1 on 2023-02-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="hr_entrenamiento",
            field=models.CharField(max_length=10),
        ),
    ]
