# Generated by Django 4.1.1 on 2023-02-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_cliente_fecha_nacimiento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="carbohidratos",
            field=models.CharField(
                default="", max_length=300, verbose_name="Carbohidratos"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="comidas",
            field=models.CharField(
                blank=True,
                default="",
                max_length=400,
                null=True,
                verbose_name="Comidas favoritas",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="enfermedades",
            field=models.CharField(
                default="", max_length=250, verbose_name="Enfermedades"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="objetivo",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=300,
                null=True,
                verbose_name="Objetivo(s)",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="proteinas",
            field=models.CharField(
                default="", max_length=300, verbose_name="Proteinas"
            ),
        ),
    ]
