# Generated by Django 4.1.1 on 2023-02-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_cliente_carbohidratos_alter_cliente_comidas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto_actual',
            field=models.TextField(blank=True, default='', verbose_name='foto panza'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dulces',
            field=models.BooleanField(default=False),
        ),
    ]
