# Generated by Django 4.1.1 on 2023-02-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cliente_foto_actual_alter_cliente_dulces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='carbohidratos',
            field=models.CharField(default='', max_length=700, verbose_name='Carbohidratos'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='proteinas',
            field=models.CharField(default='', max_length=700, verbose_name='Proteinas'),
        ),
    ]
